### ISSUE TITLE
have bug report here !

### ISSUE THREAD

**Issue by cutipu** [cutipu/HASOKI#9]
have bug report here !

**Comment by kotik1998** [comment]
Hello, i wanted to ask if there's a way to bypass uam v3 using nodejs or python requests?

**Comment by cutipu** [comment]
> Hello, i wanted to ask if there's a way to bypass uam v3 using nodejs or python requests?
Can you send me a demo website using it?

**Comment by kotik1998** [comment]
keydrop.com

**Comment by cutipu** [comment]
> keydrop.com

301 redirect with python u can use requests.follow redirect
